modLoader="javafml"
loaderVersion="[46,)"
license="ARR"
issueTrackerURL=""
[[mods]]
version="1.20.1-1.0-forge"
modId = "${mod_id}"
displayName="Paint and Innovate"

description='''

Authors:
§6Linnett§r, §5Tehword§r

Description:
A mod that our team has been preparing for a long time.
We aimed to refine every detail, both visually and lore-wise.
Explore the §oCopper Wasteland§r and §oRainbow Island§r.

...Uncover the true meaning of the word "Art"...
'''

logoFile="assets/paint_and_inovate/pai.png"

[[dependencies."${mod_id}"]]
modId="forge"
mandatory=true
versionRange="[47.1.3,)"
ordering="NONE"
side="BOTH"